// Copies the site's fonts out of the @fontsource packages into public/fonts/ and writes
// src/styles/fonts.css, so fonts are served from our own domain instead of Google.
// Only the Latin and Latin Extended subsets are kept (covers English plus transliteration marks like ā, ī).
// Re-run with `node scripts/build-fonts.mjs` if the font list changes.
import { readFileSync, writeFileSync, mkdirSync, copyFileSync, rmSync } from 'node:fs';

const fonts = [
  ['playfair-display', ['500', '500-italic', '700', '900']],
  ['source-serif-4', ['400', '400-italic', '600']],
  ['inter', ['500', '600']],
];
const keep = ['latin-ext', 'latin'];

rmSync('public/fonts', { recursive: true, force: true });
mkdirSync('public/fonts', { recursive: true });
let css = '/* Generated by scripts/build-fonts.mjs. Do not edit by hand. */\n';
for (const [pkg, variants] of fonts) {
  for (const v of variants) {
    const src = readFileSync(`node_modules/@fontsource/${pkg}/${v}.css`, 'utf8');
    for (const block of src.split(/(?=\/\* )/)) {
      const name = block.match(/^\/\* (\S+) \*\//)?.[1] ?? '';
      const subset = name.slice(pkg.length + 1).match(/^(latin-ext|latin)-\d/)?.[1];
      if (!subset || !keep.includes(subset)) continue;
      const file = block.match(/url\(\.\/files\/([^)]+\.woff2)\)/)?.[1];
      if (!file) continue;
      copyFileSync(`node_modules/@fontsource/${pkg}/files/${file}`, `public/fonts/${file}`);
      css += block
        .replace(/src: [^;]+;/, `src: url(/fonts/${file}) format('woff2');`)
        .trim() + '\n';
    }
  }
}
writeFileSync('src/styles/fonts.css', css);
console.log('fonts written');
